### PR TITLE
Cumulative initial fit

### PR DESCRIPTION
**Pull request by seabbs**
This PR switches on an initial cumulative fit that may resolve some initialisation issues for some datasets. This change requires testing before being rolled into production as small scale tests are unlikely to uncover the impact.

### CODE REVIEW

**Review by joeHickson — APPROVED** [review]
👍

**Comment by seabbs** [comment]
Tested?

**Comment by seabbs** [comment]
After running the example configuration at the bottom of run-region-updates.R I get: 

Screenshot 2020-12-10 at 13 52 53

Looks like there is an error to log issue still. 

In terms of the command line options for `run-region-updates` is the recommended option for the docs on this running: `Rscript R/run-region-updates.R --help`? I think that could do with being documented.

**Comment by seabbs** [comment]
Testing now along with updates to move code  to list.

**Comment by seabbs** [comment]
This PR is now also testing #159. 

@joeHickson could you please run ` Rscript R/run-region-updates.R -s -w` on this PR when done running things on the box (this test can't be run when other jobs are happening as it needs to assess runtime which will be confounded if other jobs are queued. The key questions that need evaluating are what is the runtime impact on all datasets (or some large subset) and are the summary results significantly different (via visual inspection and analysis of the summary `rt.csv` which would need to be posted somewhere to enable me to evaluate that.

**Comment by joeHickson** [comment]
I'll try and queue that up at lunch

**Comment by seabbs** [comment]
Thanks @joeHickson. I ran it on Friday and saw no real benefit in India but results were stable. Rolling back the testing additions and turning off cumulative fitting for now then will merge to get the list changes.

**Pull request merged**
