### PR TITLE
Make truncation set across regions

### PR DESCRIPTION
**Pull request by seabbs**
This PR adds support for region-specific truncation after discussion with @kathsherratt about the UK data. At the moment this is set to the current default everywhere (3 days) but this can now be tuned dataset by dataset as new evidence becomes available (like run time analysis etc).

### CODE REVIEW

**Comment by seabbs** [comment]
This PR adds support for region-specific truncation after discussion with @kathsherratt about the UK data. At the moment this is set to the current default everywhere (3 days) but this can now be tuned dataset by dataset as new evidence becomes available (like run time analysis etc).

**Comment by seabbs** [comment]
@joeHickson happy to merge?

**Review by joeHickson — APPROVED** [review]
looks good to me

**Comment by joeHickson** [comment]
ooo forgot to say needs documentation!

**Pull request merged**
