### PR TITLE
Update epinow2 v1.3.0

### PR DESCRIPTION
**Pull request by seabbs**
This PR makes the updates required to support `EpiNow2 1.2.1`. However, it needs to be tested prior to going into production. 

`EpiNow2 1.2.1` now outputs a `runtimes.csv` which this PR loads and reformats. It has the following variables: `region` and `time`. This change can dealt with by moving this data.frame into the named list format previously expected by downstream code (as done here) or by changing the downstream code. 

`EpiNow2 1.2.1` has several processing updates which make estimation failures hopefully less likely. It also has several model changes which should make results more stable.

### CODE REVIEW

**Comment by joeHickson** [comment]
I'll pop this on the server for a test

**Comment by joeHickson** [comment]
closes #83 (linking)

**Comment by joeHickson** [comment]
[2] "  reached elapsed time limit"                    
[3] "In addition: Warning message:"                   
[4] "In storage.mode(default) <- type :"              
[5] "  NAs introduced by coercion to integer range"   
error occurred during calling the sampler; sampling not done
Timing stopped at: 2548 3.389 1801
Timing stopped at: 2548 3.389 1802
[1] "Error in sampler$call_sampler(args_list[[i]]) : "
[2] "  reached elapsed time limit"                    
[3] "In addition: Warning message:"                   
[4] "In storage.mode(default) <- type :"              
[5] "  NAs introduced by coercion to integer range"   
error occurred during calling the sampler; sampling not done
Timing stopped at: 892.9 1.586 1801
Timing stopped at: 893 1.587 1802
[1] "Error in sampler$call_sampler(args_list[[i]]) : "
[2] "  reached elapsed time limit"                    
[3] "In addition: Warning message:"                   
[4] "In storage.mode(default) <- type :"              
[5] "  NAs introduced by coercion to integer range"   
error occurred during calling the sampler; sampling not done
Timing stopped at: 2.223 0.46 1801
Timing stopped at: 2.386 0.46 1801
2020-10-19 13:16:04 INFO Completed regional estimates
2020-10-19 13:16:04 INFO Regions with estimates: 1
2020-10-19 13:16:04 INFO Regions with runtime errors: 8
2020-10-19 13:16:04 INFO Producing summary
2020-10-19 13:16:04 INFO Saving summary to : subnational/canada/cases/summary
2020-10-19 13:16:04 INFO Errors caught whilst generating summary statistics: 
2020-10-19 13:16:04 INFO Error in .f(...): Only one of results_dir and regional_output should be specified

2020-10-19 13:16:04 INFO Saving timings information to : subnational/canada/cases/national
2020-10-19 13:16:04 DEBUG resetting future plan to sequential
2020-10-19 13:16:04 DEBUG skipping location colombia as it is not in the include list
2020-10-19 13:16:04 DEBUG skipping location germany as it is not in the include list
2020-10-19 13:16:04 DEBUG skipping location india as it is not in the include list
2020-10-19 13:16:04 DEBUG skipping location italy as it is not in the include list
2020-10-19 13:16:04 DEBUG skipping location russia as it is not in the include list
2020-10-19 13:16:04 INFO processing outcome log
Error: `false` must be NULL, not a `Date` object.
Backtrace:
    █
 1. └─global::run_regional_updates(datasets = datasets, args = args)
 2.   └─global::rru_log_outcome(outcome)
 3.     └─dplyr::if_else(...)
 4.       └─dplyr:::replace_with(...)
 5.         └─dplyr:::check_type(val, x, name)
 6.           └─dplyr:::glubort(header, "must be {friendly_type_of(template)}, not {friendly_type_of(x)}.")
Warning message:
In storage.mode(default) <- type :
  NAs introduced by coercion to integer range
Execution halted


Running it again with verbosity turned up to see what the problem is.

**Comment by seabbs** [comment]
It looks like there were two issues identified and fixed by @medewitt and @sbfnk respectively. One linked to fitting ( `fit_model` due to an odd interaction with timing out and `rstan` (we think)) and one due to bad code displine on my part in `regional_summary` (in setting up a plot saving function). The tagged version has been updated so if you could rerun the test with an updated install of `EpiNow2 1.2.1` that would be great.

**Comment by joeHickson** [comment]
I'll set that re-running now

**Comment by joeHickson** [comment]
```
2020-10-20 11:34:55 TRACE dataset canada had no data to process
2020-10-20 11:34:55 TRACE status record exists for canada
Error: `false` must be NULL, not a `Date` object.
Backtrace:
    █
 1. └─global::run_regional_updates(datasets = datasets, args = args)
 2.   └─global::rru_log_outcome(outcome)
 3.     └─dplyr::if_else(...)
 4.       └─dplyr:::replace_with(...)
 5.         └─dplyr:::check_type(val, x, name)
 6.           └─dplyr:::glubort(header, "must be {friendly_type_of(template)}, not {friendly_type_of(x)}.")
```

so it's still failling - I think the updated record is the wrong type in one of the columns but it doesn't say which - it would need debugging to look at the record it's trying to insert into the list.

**Comment by seabbs** [comment]
So is this an error in the processing code we think or in EpiNow2? I wrote the update to the processing code without running so extremely likely to not be correct.

**Comment by seabbs** [comment]
agreevon your diagnosis. I assume/hope its a mistake with my changes to runtimes.csv.

**Comment by joeHickson** [comment]
I had similar when I failed to get the column to contain the right POSIXct object type - I expect this is similar but with a DATE type - the table has fixed column types and complains if you get it wrong so hopefully it's just something with how you have mapped the data over. Catching outcomes and debugging it is going to be the easiest way.

**Comment by seabbs** [comment]
Any luck tracking this down. I haven't seen any `EpiNow2` issues elsewhere but that doesn't mean there aren't any.

**Comment by joeHickson** [comment]
It looks like it might be not handling when a location fails - that seems to be a pattern when I am also getting this error (but I have not properly dug)

**Comment by seabbs** [comment]
It would be good to get this moving if possible. If you have a snapshot of the logs I am happy to look through the code to try and diagnose the issue. 

We are seeing that the switch to quantiles is giving much more sensibly shaped credible intervals than the previous high density regions (more robust over time) so it would be good to get this change into the estimates etc.

**Comment by joeHickson** [comment]
running a test with this updated to latest to see what happens and pull the logs

**Comment by joeHickson** [comment]
```
2020-10-26 16:05:41 INFO Producing estimates for: Alberta, British Columbia, Manitoba, New Brunswick, Newfoundland and Labrador, Nova Scotia, Ontario, Quebec, Saskatchewan
2020-10-26 16:05:41 INFO Regions excluded: Northwest Territories, Nunavut, Prince Edward Island, Repatriated Travellers, Yukon
2020-10-26 16:05:41 TRACE calling future apply to process each region through the run_region function
2020-10-26 16:05:41 INFO Showing progress using progressr. Modify this behaviour using progressr::handlers.
2020-10-26 16:35:58 INFO Completed regional estimates
2020-10-26 16:35:58 INFO Regions with estimates: 7
2020-10-26 16:35:58 INFO Regions with runtime errors: 2
2020-10-26 16:35:58 INFO Producing summary
2020-10-26 16:35:58 INFO Saving summary to : subnational/canada/cases/summary
2020-10-26 16:35:58 TRACE Getting regional results
2020-10-26 16:35:58 TRACE Summarising results
2020-10-26 16:35:58 INFO Errors caught whilst generating summary statistics: 
2020-10-26 16:35:58 INFO Error: `device` must be NULL, a string or a function.

2020-10-26 16:35:58 INFO Saving timings information to : subnational/canada/cases/national
2020-10-26 16:35:58 WARN simpleWarning in gsub("~m", msg, message, fixed = TRUE): argument 'replacement' has length > 1 and only the first element will be used

2020-10-26 16:36:04 DEBUG canada: dataverse exists so just update
2020-10-26 16:36:04 TRACE replacing file subnational/canada/cases/summary/cases_by_infection.csv
...
2020-10-26 16:36:22 TRACE replacing file subnational/canada/cases/summary/summary_table.csv
2020-10-26 16:36:23 INFO canada: publishing
2020-10-26 16:36:53 DEBUG skipping location colombia as it is not in the include list
2020-10-26 16:36:53 DEBUG skipping location germany as it is not in the include list
2020-10-26 16:36:53 DEBUG skipping location india as it is not in the include list
2020-10-26 16:36:53 DEBUG skipping location italy as it is not in the include list
2020-10-26 16:36:53 DEBUG skipping location russia as it is not in the include list
2020-10-26 16:36:53 INFO processing outcome log
2020-10-26 16:36:53 TRACE loading the existing file
2020-10-26 16:36:53 TRACE reformatting the dates back to being dates
2020-10-26 16:36:53 TRACE loading the existing status file
2020-10-26 16:36:53 TRACE reformatting the dates back to being dates
2020-10-26 16:36:53 TRACE processing results for canada
2020-10-26 16:36:53 TRACE dataset canada had no data to process
2020-10-26 16:36:53 TRACE status record exists for canada
2020-10-26 16:36:53 ERROR Error: `false` must be NULL, not a `Date` object.
```

**Comment by seabbs** [comment]
I don't see this issue anywhere else? I think the failing error is in the timings processing code in this repo.

**Comment by joeHickson** [comment]
Todays poking has made some progress:
```
2020-10-29 14:43:48 TRACE Summarising results
2020-10-29 14:43:48 INFO Errors caught whilst generating summary statistics: 
2020-10-29 14:43:48 INFO Error: `device` must be NULL, a string or a function.

2020-10-29 14:43:48 INFO Saving timings information to : subnational/canada/cases/national
2020-10-29 14:43:48 WARN canada: simpleWarning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 2 has 5 rows but longest item has 9; recycled with re
mainder.

2020-10-29 14:43:48 WARN simpleWarning in gsub("~m", msg, message, fixed = TRUE): argument 'replacement' has length > 1 and only the first element will be used
```

It seems there's a possible bug where if you had failures it tries to process something in the summary based on the number it wants not the number it got. 

All those errors and the eventual crash are coming from within regional_summary as it is not hitting the trace line I now have immediately following it ( https://github.com/epiforecasts/covid-rt-estimates/pull/96/files#diff-31e37843456589f8f25be8078e415c2d276bf0da7d57c4d48b398f76862c9cbfR134 )

**Comment by joeHickson** [comment]
@seabbs Where does epinow write it's errors to currently?

**Comment by seabbs** [comment]
It should use your logging set up and send the logs where you specify externally if logs  = NULL

**Comment by seabbs** [comment]
I am getting close to releasing `1.3.1` shall I make a tag and we switch to testing that? It has the final interface changes so interaction with EpiNow2 will be stable going forward.

**Comment by joeHickson** [comment]
latest error:
2020-11-17 10:44:47 TRACE Getting regional results
2020-11-17 10:44:47 WARN simpleWarning in gzfile(file, "rb"): cannot open compressed file 'subnational/united-states/cases/national/runt
imes.csv/latest/summarised_estimates.rds', probable reason 'Not a directory'

**Comment by seabbs** [comment]
that is an uncaught exclusion as runtimes is a csv and so doesn't have estimates but shouldn't be a failing error?

**Comment by joeHickson** [comment]
it's looking for an RDS file inside a subfolder within a .csv which seems a bit wonky.
subnational/united-states/cases/national/runtimes.csv/latest/summarised_estimates.rd

**Comment by seabbs** [comment]
it is within an error catch so I don't think it is causing an error here. I agree it could do with being caught so it doesn't occur.

**Comment by seabbs** [comment]
@joeHickson I have updated to the new args from `1.3.0` and made a pre-release for it in the EpiNow2 repo. 

The only difference here to what we usually use is the `future = TRUE` arg which might be causing problems (running stan in parallel and then merging posterior samples back into a single model). Potentially might need to fall back to the traditional behaviour which will sacrifice the ability to kill some chains but not all but may reduce the overall complexity.

**Comment by seabbs** [comment]
The first log issue looks like it may have come from here: https://github.com/epiforecasts/covid-rt-estimates/blob/f22593aae87647ba2ed084c6a79270f9eacab415/R/run-region-updates.R#L239

but has potentially been fixed. The second (`device` must be NULL, a string or a function) is from plot saving using `ggsave` and means something other than the string it should be is being passed to the device arg.  In the code (https://github.com/epiforecasts/EpiNow2/blob/c12b5c2432c44b65db2b3844ca0f5dc7f8cad5de/R/summarise.R#L140) I see nothing obvious triggering this. If this pops up again I think the easiest solution is an interactive debug of `regional_summary` on saved results as not clear what could be causing this.

**Comment by joeHickson** [comment]
I'm loading it into the test container now.

**Comment by seabbs** [comment]
🤞

**Comment by joeHickson** [comment]
do you have 10 mins? I could give you a call and talk you through how I use the test container.

**Comment by seabbs** [comment]
yes sounds good.

**Comment by joeHickson** [comment]
I have sent you a meeting invite that we can use to jump on a teams call

**Comment by joeHickson** [comment]
Still the same. Interestingly I could see that it was still processing some of the regions after it had crashed - which is not how I thought the parallel stuff worked. You can see in the log the parallel threads still login stan warnings before and after the main script decides to plough onwards.

```
to find out why this is a problem and how to eliminate them. - 
2020-11-18 20:03:13 WARN Alberta (chain: 2): Examine the pairs() plot to diagnose sampling problems
 - 
2020-11-18 20:03:19 ERROR Error in as.environment(where): using 'as.environment(NULL)' is defunct

2020-11-18 20:03:19 WARN simpleWarning in gsub("~m", msg, message, fixed = TRUE): argument 'replacement' has length > 1 and only the fir
st element will be used

2020-11-18 20:03:19 TRACE analyse results
2020-11-18 20:03:19 INFO processing outcome log
2020-11-18 20:03:19 TRACE loading the existing file
2020-11-18 20:03:19 TRACE reformatting the dates back to being dates
2020-11-18 20:03:19 TRACE loading the existing status file
2020-11-18 20:03:19 TRACE reformatting the dates back to being dates
2020-11-18 20:03:19 TRACE processing results for canada
2020-11-18 20:03:19 ERROR No subregions recorded in outcome for canada
2020-11-18 20:03:19 TRACE writing file
2020-11-18 20:03:19 TRACE process derivative datasets
2020-11-18 20:03:19 INFO run complete
2020-11-18 20:03:19 WARN British Columbia (chain: 5): There were 5 divergent transitions after warmup. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
to find out why this is a problem and how to eliminate them. - 
2020-11-18 20:03:19 WARN British Columbia (chain: 5): Examine the pairs() plot to diagnose sampling problems
 - 
2020-11-18 20:03:43 WARN Alberta (chain: 3): There were 9 divergent transitions after warmup. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
to find out why this is a problem and how to eliminate them. - 
2020-11-18 20:03:43 WARN Alberta (chain: 3): Examine the pairs() plot to diagnose sampling problems
```

**Comment by seabbs** [comment]
as discussed updated with `future = FALSE` - may help or it may not.

**Comment by seabbs** [comment]
Looks like there was a logic knot (i.e a fancy bug) in the interaction between returning output, generating summaries and timings spotted by @sbfnk [here](https://github.com/epiforecasts/EpiNow2/issues/175) and resolved [here](https://github.com/epiforecasts/EpiNow2/pull/176). I've updated the tag and revert back to `future = TRUE` (though this still may cause issues potentially). Will update once CI finsihes on EpiNow2 and I have reviewed again in the morning.

**Comment by joeHickson** [comment]
Thanks @seabbs - it looks like it turned into a late one. Let me know when it's ready and I'll pull it down and see what happens

**Comment by seabbs** [comment]
Should be ready now I think. 🤞

**Comment by joeHickson** [comment]
I'm still getting that error. does it need description updating for a newer epinow version?

**Comment by seabbs** [comment]
Ah looks like you need to also delete the tag as well as the release in order to change the reference commit. Should now be updated and correct.

**Comment by joeHickson** [comment]
I kicked of the global cases to re-run after the last failure so it'll be a while before the box has spare capacity but once it does I'll try again.

**Comment by joeHickson** [comment]
Ok progress - back to this error again:
2020-11-19 19:32:05 INFO Saving timings information to : subnational/canada/cases/national
2020-11-19 19:32:05 INFO Saving summary to : subnational/canada/cases/summary
2020-11-19 19:32:05 INFO Extracting results from: subnational/canada/cases/national
2020-11-19 19:32:05 WARN simpleWarning in gzfile(file, "rb"): cannot open compressed file 'subnational/canada/cases/national/runtimes.cs
v/latest/summarised_estimates.rds', probable reason 'Not a directory'

I think its get.R:11- but I haven't debugged yet to see if I can figure out why line 15 isn't filtering it

**Comment by seabbs** [comment]
So this is caught here: https://github.com/epiforecasts/EpiNow2/blob/251f2f1b0251a6fa78d3703484f4fc51cbacd550/R/get.R#L117 and therefore is a warning not an error. I will add a catch to remove it now but I think it unlikely its the root cause of a run failure. 

Can you see updates to the summary folder? What updated and what didn't?

**Comment by joeHickson** [comment]
I think it writes L165 (INFO Extracting results from: ....) but it doesn't get as far as L176 in https://github.com/epiforecasts/EpiNow2/blob/25bcd449134c41c0deed69300b08a5b542e7a2ec/R/summarise.R

No files have been written to the summary dir

**Comment by joeHickson** [comment]
That looked like it ran!

**Comment by joeHickson** [comment]
@seabbs can you sanity check those results? I can see graphs but aside from that I couldn't tell you if they are as expected! I'm wary of saying lets go on a friday afternoon but given the rest of the issues I'm tempted... 
image

**Review by joeHickson — APPROVED** [review]

**Comment by seabbs** [comment]
Love the post it. To me these are all looking as I would expect. @sbfnk thoughts? I don't think `1.2.0` is suddenly going to start working smoothly and it might be easier to debug if working from a common code base. 

My vote is deploy and 🙏

**Comment by seabbs** [comment]
https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/update-epinow2-v1.2.1/subnational/united-kingdom/cases/summary/rt_plot.png

https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/update-epinow2-v1.2.1/subnational/united-kingdom/cases/summary/reported_cases_plot.png

https://raw.githubusercontent.com/epiforecasts/covid-rt-estimates/update-epinow2-v1.2.1/subnational/united-kingdom/cases/summary/infections_plot.png

**Comment by joeHickson** [comment]
comparing master reported_cases_plot - 
image
Master left, this branch right

**Comment by joeHickson** [comment]
There's some definite wierdness on the uncertainties on the rt plot - check out midlands / south west for going all a bit lumpy bumpy
image

**Comment by seabbs** [comment]
`1.3.0` uses quantiles and `1.2.0` uses high density regions to summarise uncertainty so some changes in the credible intervals are probably be expected. The slightly odd waggles in the uncertainty are from semi-plausible osciallations in the gaussian process. We haven't nailed down if these are okay plausible edge case behaviour or a model issue yet but its not an unexpected result.

**Comment by joeHickson** [comment]
Good to know - not been particularly familiar with the modelling code all I can do is apply an eyeball and ask the silly questions ;)

**Comment by joeHickson** [comment]
Shall I back out those two test commits?

**Comment by seabbs** [comment]
Chatted with @sbfnk we think merge in and 🤞

**Comment by joeHickson** [comment]
@seabbs do you want to grab a beer, light the blue touch paper and retire for the night?

**Comment by seabbs** [comment]
🥂

**Pull request merged**
