### PR TITLE
Add truncation for UK

### PR DESCRIPTION
**Pull request by kathsherratt**
Aims to address issue #88 by increasing truncation to 5 days in the UK test-positive cases data. Deaths and admissions Rts don't look like they are suffering the same issue so no changes there.

Discussed this with @sbfnk, where we reviewed UK data and recent estimates of delays from lab test to report. Decision was to truncate at 5 days: truncation at 3 days looks insufficient, 4 days is enough to capture most of the data, plus 1 day feed through into the public PHE dataset.

@joeHickson - from what I can see in the code it looks like all I need to do here is add an extra `truncation` parameter, that gets fed through into the cleaning functions (where the default param is set to 3). I have opened this PR to do this - would that work?

### CODE REVIEW

**Comment by joeHickson** [comment]
Hi @kathsherratt it should be as simple as that! This should be clearer once #91 is done

**Review by joeHickson — APPROVED** [review]
looks good to me

**Comment by joeHickson** [comment]
I'll try and hook this branch onto the box to give the data a test process so you can confirm the results vs master

**Comment by joeHickson** [comment]
closes #88

**Comment by joeHickson** [comment]
Hi @kathsherratt,
Can you check the outcome looks good? 

I had two failing regions but I think that's the same error we are seeing on master from time to time.

2020-10-19 09:15:26 INFO Runtime error in East of England : The following elements of 'sflist' do not contain samples: 3. - rstan::sflist2stanfit, fit
2020-10-19 09:15:26 INFO Runtime error in England : The following elements of 'sflist' do not contain samples: 2. - rstan::sflist2stanfit, fit

**Comment by kathsherratt** [comment]
Thanks very much for running this Joe. Interesting that even with 5 day truncation there is still a downturn in the more recent estimates (even before the partial data sets in). 

My opinion is probably that we should use the 5 day case data truncation for the UK in the master - although this doesn't exactly "fix" the unexpected results, we at least know that it's more reliable than the 3 day default.

In the meantime I have flagged this to @sbfnk and I guess @seabbs might also want to take another look when he is back from AL.

**Comment by joeHickson** [comment]
thanks @kathsherratt - I'll get it merged in

**Comment by joeHickson** [comment]
force push to re-write history and remove test data commit.

**Comment by joeHickson** [comment]
I'm not sure on the numbers elsewhere but Exeter uni was driving all the cases down here and it's dropping off quite a bit - perhaps other unis are having similar post freshers?
https://www.devonlive.com/news/devon-news/university-exeter-coronavirus-cluster-drops-4621084 (sorry for the poor quality of publication...)

**Comment by seabbs** [comment]
Good point and I think that is probably the case. Though really this points out the issues of testing bias rather than being a good sign sadly....

**Comment by joeHickson** [comment]
We shall have to wait a couple of weeks for the admissions data to catch up and see

**Comment by seabbs** [comment]
So if the age distribution is constant what we are doing should be adjusting for that delay. However, it's likely not and we will see transfer from young to old meaning a couple of weeks wait! 

@kathsherratt could you drop a link to your preprint in the readme + a short sentence on how to interpret estimates from multiple data sources? Seems like it could be useful for data consumers.

**Pull request merged**
