### PR TITLE
Collate across new uk data sources

### PR DESCRIPTION
**Pull request by kathsherratt**
Added `utils/collate-rt-summary.R`, a function to collate across sources within a region. This addresses #63.
 - I imagine this needs editing to fit with the infrastructure - please do suggest. 
 - Also adds a new dependency on `purrr` - open to a re-write if this is an issue.

### CODE REVIEW

**Comment by seabbs** [comment]
Can you merge master into this - it looks like the changes from the branch aren't synced up properly.

**Comment by seabbs** [comment]
Ah right I see its because its on the same branch as previous work.

**Comment by seabbs** [comment]
Nice stuff - spot on! 

I made a few updates and tweaks to use just `data.table` and generalize to any target in the summary folder. Coded in the github editor so a bit YOLO I am afraid. Just need to move it from the general `utils` folder into the `R/utilities.R` store - sorry confusing layout from me I am afraid. 

It might be an idea to keep the repo history clean and avoid merge issues to close this PR, and open another with the function in a new branch based on master (I can see this getting confusing 😄).

**Comment by kathsherratt** [comment]
Ah perfect - thanks for re-writing in data.table! Closing this PR before I re-open from a clean branch.

**Pull request closed without merging**
