### PR TITLE
I103 dataverse for last upto date

### LINKED ISSUE #103: Use dataverse for data up to date (remove the need for last-update/*.rds)
We could get the latest data from dataverse (latest published data) rather than rely on committing local .rds files.
Blocked by #80 

update the publish script to include the dates for the source data. This is additional data in the get_fields_list function.
```R
list(
            typeName = "timePeriodCovered",
            multiple = TRUE,
            typeClass = "compound",
            value = list(
              list(
                timePeriodCoveredStart = list(
                  typeName = "timePeriodCoveredStart",
                  multiple = FALSE,
                  typeClass = "primitive",
                  value = oldest_data_date
                ),
                timePeriodCoveredEnd = list(
                  typeName = "timePeriodCoveredEnd",
                  multiple = FALSE,
                  typeClass = "primitive",
                  value = newest_data_date
                )
              )
``` 

Update the check_for_update function (utils.R) to handle the checking (probably via a new function). If there are no local .rds files and there is a dataverse config set up then get the "timePeriodCoveredEnd" for the dataset (look at how publish checks for an existing dataset - the same method can be used).
This needs to handle the following as no latest date:
- no config for dataverse
- unable to find a dataset
- unable to find timePeriodCoveredEnd on the dataset

Delete the last-update folder and add it to .gitignore (it will still be generated to allow non-publishing datasets to use it but should only apply to their local datasets)

### PR DESCRIPTION
**Pull request by joeHickson**
closes #103

### CODE REVIEW

**Comment by joeHickson** [comment]
I think this is now ready for a review

**Review by seabbs — APPROVED** [review]
:+1:

**Comment by seabbs** [comment]
ready to be merged?

**Comment by joeHickson** [comment]
I think so

**Comment by seabbs** [comment]
Close or merge?

**Comment by joeHickson** [comment]
I'd probably go merge - it's to reduce dependency on local files long term but given dataverse being a pain you could convince me either way.

**Pull request closed without merging**
