### PR TITLE
Full timeseries

### LINKED ISSUE #15: Add estimates for a complete time series in each country/subnational region
Due to computational and storage constraints, it is not feasible to run the complete time series every day with our current resources. For this reason, we have shifted our daily updates to focus on a rolling window of the last 3 months of data. Many users may be interested in the complete time series - please respond to this issue in order for us to assess the priority of this requirement.  

We are considering two solutions to this issue: 

1. Piecing together daily estimates from rolling model fits
2. Running less frequent complete time series runs and linking these to our real-time estimates.

### PR DESCRIPTION
**Pull request by joeHickson**
add -full versions of all the datasets

closes #15

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
LGTM. Nice!

**Review by seabbs — APPROVED** [review]

**Comment by seabbs** [comment]
Hi Joe, did you test this? 

I have spent today trying to debug what has brought down the pipeline. Looking at the logs it looks like sublocation filtering is being triggered even when empty which leads to an empty data frame and a obscure failure message.

The sublocation filter is built out of matching location and includes namin. Running through with debug I get sent to the Canada-full data but the Canada class in the includes list. This leads to a NULL in includes_subregions and an error that matches what I see from the server logs. 

Screenshot 2021-05-11 at 10 07 22

**Comment by joeHickson** [comment]
I tested the full but bet I failed to test an original one...

**Comment by seabbs** [comment]
no worries the way R6 classes update is pretty damn strange and hard to debug (I think it is one of the reasons they are working on R7).

**Pull request merged**
