### PR TITLE
Add log analysis tool

### PR DESCRIPTION
**Pull request by joeHickson**
Some python to help with processing the log files. I stuck it in a utils folder in the basis it would be available for others. Python is in the stack on the docker container.

To run:

python3 /path/to/utils/runtime_analysis.py /path/to/log/file.log

### CODE REVIEW

**Comment by seabbs** [comment]
This looks good (as far as I can tell my 🐍 is terrible). Give me a ping when ready for a more formal review.

**Comment by joeHickson** [comment]
@seabbs I'll request @JAllen42 gives it a first review then. I'm afraid we use a lot of python for scripting at the MO so it's my default for a quick bit of string parsing. I'm sure it must be possible in R but it was quicker to bash it out in python given it's only a debugging util.

**Comment by seabbs** [comment]
Not a problem - sounds good.

**Review by JAllen42 — COMMENTED** [review]
Looks good to me. I could run it and it produced the results I expected it to.

The log file in my local copy is the result of multiple runs, so I don't know if it is worth mentioning that in this case it will print the most recent run time for each location, and that a negative value can mean that the most recent run for a location didn't finish.

**Review by seabbs — APPROVED** [review]

**Pull request merged**
