### PR TITLE
I116 summary dataset definitions

### LINKED ISSUE #116: Structure for specifying summary datasets
Possible solution (for discussion):

Have a new summary list that lives alongside the datasets in dataset-list.R - This is a list of new "summary" objects.
The summary object contains:

list of dataset names that it requires (in the format dataset/* OR dataset/sublocation)
details of where to put the results (name, folder location, publication data (if post dataverse), etc)
incremental update flag (run after every dataset or only once all datasets have completed)
Update collate_estimates to work off this summary object, getting it's summary data from the datasets indicated (filtering if required to only the chosen sublocations) and outputting as defined.

Extend the run-region-update hack to trigger these:

If the summary is non-incremental and the current location is the last on the given list of dataset locations. (This goes away with new infrastructure as it will be scheduled as a separate job.)
If the summary is incremental and the current location is in the list.
This allows for summary datasets that are not within a single location / dataset folder (currently it is tied to all datasets within a particular folder) and also for subsets to be summarised.

This could allow for summaries like:
Europe National Cases (subset from global cases)
North America Cases (combine USA & Canada at state/province level)
UK All Types (cases + deaths + hospitalisations)

If this is tackled post- dataverse publication then get the summary data from there (if dataverse is configured) rather than local disk and record the source dataset id's for inclusion in the publication metadata (you can link to the source data used to generate the dataset so might as well point back to the various datasets).

This blocks #92 and has been split from the discussion on that ticket

### PR DESCRIPTION
**Pull request by joeHickson**
closes #116 

"Collated Derivative" = Summary dataset produced by stitching together multiple other datasets results.

Note UK summary changes to more standardised format - currently this outputs a dated file in the old archival style. With this change it will just output united-kingdom/collated/rt.csv

This includes publishing the collated dataset to DV - https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/6GNVT2 

This task also brings a lot of tidy up in areas that needed expanding with the collated derivatives - entities are broken out to individual files, lists are in their own subfolder too. 

Also switched to using 
```R
if (!exists("add_uk", mode = "function")) source(here::here("R", "utils.R")) 
```
at the top of files to list required includes - this should ensure they are only pulled in once but guarantees they are available in that file. By starting to do this in each file it's possible to pick and choose which bits you use when cobbling random test scripts together and ensures each piece can be used in more isolation.
e.g.
`source("R/collate-derivative.R")` doesn't require to run all the source(x) from the top of run-region-updates before calling it

This is handy for testing / debugging as you can call the script much like it would be in the bigger suite
```R
source("R/collate-derivative.R") # get the script to collate derivatives
source("data/runtime/config.R") # load the dataverse config (optional, allows testing of publication)
source("R/lists/collated-derivative-list.R") # load the list of defined collated derivatives
futile.logger::flog.threshold(futile.logger::TRACE) # set your log level for debugging
collate_derivative(COLLATED_DERIVATIVES[[1]]) # call the function the same way it is from run-region-updates.R and check it works
```

### CODE REVIEW

**Review by seabbs — APPROVED** [review]
Nice. :+1: in principle but need to wait until @sbfnk updates users of data location. @sbfnk this update changes the location of the collated UK csv that should be used by data consumers to be on the dataverse.

**Comment by joeHickson** [comment]
Todo: Reimplement old uk summary temporarily

**Comment by joeHickson** [comment]
reintroduced uk method as a deprecated block for the time being

**Comment by joeHickson** [comment]
@seabbs I think this is good to merge

**Comment by seabbs** [comment]
Nice stuff - all looks good to me.

**Pull request merged**
